# Generated by Django 4.2 on 2023-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes1',
            name='Fecha_na',
            field=models.DateField(blank=True, null=True),
        ),
    ]
