# Generated by Django 4.2 on 2023-05-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_pacientes1_fecha_na'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.UUIDField(help_text='id unico para este documento en los archivos', primary_key=True, serialize=False)),
                ('NomFile', models.CharField(max_length=100)),
                ('url_archi', models.CharField(max_length=100)),
            ],
        ),
    ]
