# Generated by Django 4.1.7 on 2023-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_pacientes1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pacientes1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes_imagen/'),
        ),
    ]
