# Generated by Django 4.1.7 on 2023-05-23 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_documentos_fecha_subida_alter_pacientes1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='url_archi',
        ),
        migrations.AddField(
            model_name='documentos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='archivos/pacientes'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes1'),
        ),
    ]
